# Generated by Django 5.1.7 on 2025-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('it', 'IT'), ('hr', 'Human Resource'), ('finance', 'Finance')], max_length=20),
        ),
    ]
