# Generated by Django 5.1.7 on 2025-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Information Technology', 'IT'), ('Human Resource', 'human Resource'), ('Finance', 'finance')], max_length=22),
        ),
    ]
