# Generated by Django 5.1.7 on 2025-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('supervisorial', 'Supervisorial'), ('humna Resource', 'HR'), ('administrative', 'Administrative')], max_length=100),
        ),
    ]
