# Generated by Django 5.1.7 on 2025-05-11 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtraining',
            name='at_employee',
            field=models.ForeignKey(limit_choices_to={'user_role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competency',
            name='comp_employee',
            field=models.ForeignKey(limit_choices_to={'user_role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EnrolledTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_employee', models.ForeignKey(limit_choices_to={'user_role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_trainings', to=settings.AUTH_USER_MODEL)),
                ('en_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_employees', to='api.training')),
            ],
        ),
        migrations.CreateModel(
            name='LearningActionPlan',
            fields=[
                ('lap_ID', models.AutoField(primary_key=True, serialize=False)),
                ('lap_takeaways', models.TextField()),
                ('lap_goal', models.TextField()),
                ('lap_plan', models.TextField()),
                ('lap_support', models.TextField()),
                ('lap_outcome', models.TextField()),
                ('lap_status', models.CharField(choices=[('to_evaluate', 'To be Evaluated'), ('approved', 'Action Plan Approved'), ('rejected', 'Action Plan Rejected')], default='to_evaluate', max_length=20)),
                ('lap_employee', models.ForeignKey(limit_choices_to={'user_role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_laps', to=settings.AUTH_USER_MODEL)),
                ('lap_supervisor', models.ForeignKey(limit_choices_to={'user_role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_laps', to=settings.AUTH_USER_MODEL)),
                ('lap_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.training')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_ID', models.AutoField(primary_key=True, serialize=False)),
                ('progress_status', models.CharField(choices=[('to_evaluate', 'To be Evaluated'), ('training_attended', 'Training Attended'), ('training_not_attended', 'Training Not Attended'), ('lap_approved', 'Action Plan Approved'), ('lap_rejected', 'Action Plan Rejected'), ('successful', 'Successful'), ('failed', 'Failed')], default='to_evaluate', max_length=100)),
                ('progress_employee', models.ForeignKey(limit_choices_to={'user_role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_as_employee', to=settings.AUTH_USER_MODEL)),
                ('progress_evaluator', models.ForeignKey(limit_choices_to={'user_role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_as_evaluator', to=settings.AUTH_USER_MODEL)),
                ('progress_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learningactionplan')),
                ('progress_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.training')),
            ],
        ),
    ]
