# Generated by Django 5.1.7 on 2025-05-12 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_supervisor_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningactionplan',
            name='lap_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
