# Generated by Django 5.1.7 on 2025-05-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_learningactionplan_lap_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningactionplan',
            name='lap_supervisor',
        ),
    ]
