# Generated by Django 5.1.7 on 2025-05-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_learningactionplan_lap_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningactionplan',
            name='lap_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
