# Generated by Django 5.1.7 on 2025-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_learningactionplan_lap_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningactionplan',
            name='lap_timeframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
