# Generated by Django 5.1.7 on 2025-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_learningactionplan_lap_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningactionplan',
            name='lap_timeframe',
            field=models.TextField(),
        ),
    ]
