# Generated by Django 5.1.7 on 2025-05-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_learningactionplan_lap_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='progress_evaluator',
        ),
    ]
